# Nombre de la aplicacion
spring.application.name=eureka-server

# Puerto en el que se ejecutara el servidor Eureka
server.port=8761

# Configurar para que no se registre a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL de Eureka para otros clientes
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuracion opcional para el dashboard
eureka.server.enable-self-preservation=false